InitialDelay: 5
SiegeSchedule:
  startCity1:  
    Day: 3  
    Hour: 21
    Minute: 30
    Second: 0
    CityName: Yorend
    Command1: say Siege on City1 starts now!
    Command2: say placeholder
  endCity1:  
    Day: 3
    Hour: 21
    Minute: 32
    Second: 0
    Command1: say Siege on City1 ends!
    Command2: say placeholder
