name: SiegeMode
main: MrInfroGusko.ConsoleScheduler.ConsoleScheduler
version: 1.2
author: MrInfro, Gusko

commands:
  sm:
    aliases: [siegemode]
    description: SiegeMode Commands
    usage: /sm
    
permissions:
  SiegeMode.use:
     description: Use the plugin.
     default: op