name: SiegeMode
main: MrInfroGusko.SiegeMode.SiegeMode
version: RC-1.0
author: MrInfro, Gusko

commands:
  sm:
    aliases: [siegemode]
    description: SiegeMode Commands
    usage: /sm
    
permissions:
  SiegeMode.use:
     description: Use the plugin.
     default: op
